listen_addresses = '*'
port = 5432

max_connections = 150

# ---------------------------
# MEMORIA
# ---------------------------
shared_buffers = 512MB
work_mem = 16MB
maintenance_work_mem = 512MB
effective_cache_size = 1GB

# ---------------------------
# WAL / CHECKPOINTS
# ---------------------------
wal_level = replica
wal_buffers = 32MB
checkpoint_completion_target = 0.9
checkpoint_timeout = 15min
max_wal_size = 2GB
min_wal_size = 1GB

# ---------------------------
# RENDIMIENTO
# ---------------------------
effective_io_concurrency = 150
random_page_cost = 1.1
seq_page_cost = 1.0

# ---------------------------
# AUTOVACUUM
# ---------------------------
autovacuum = on
autovacuum_max_workers = 4
autovacuum_naptime = 20s
autovacuum_vacuum_scale_factor = 0.02
autovacuum_analyze_scale_factor = 0.01

# ---------------------------
# PARALELISMO
# ---------------------------
max_worker_processes = 2
max_parallel_workers = 2
max_parallel_workers_per_gather = 2

# ---------------------------
# LOGS
# ---------------------------
logging_collector = on
log_directory = 'log'
log_filename = 'postgresql-%Y-%m-%d.log'
log_min_duration_statement = 300ms
log_checkpoints = on
log_lock_waits = on
log_file_mode = 0640
log_line_prefix = '%m [%p] %u@%d '
log_connections = on
log_disconnections = on
# ---------------------------
# EXTENSIONES
# ---------------------------
shared_preload_libraries = 'pg_stat_statements'
track_activity_query_size = 2048

# ---------------------------
# LOCALE / TIME
# ---------------------------
timezone = 'UTC'
